"use client"
import Navbar from '@/components/navbar'
import type { AppProps } from 'next/app'
import { ThemeProvider } from "next-themes"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='min-h-screen'>
      <head>
        
      </head>
      <body className={inter.className}>
        <ThemeProvider enableSystem={true} attribute='class'>
        <Navbar></Navbar>
        {children}
        </ThemeProvider>
        </body>
    </html>
  )
}
